package events;

import publishers.AbstractPublisher;
import publishers.ConcretePublisher;
import strategies.publisher.StrategyFactory;


/**
 * @author kkontog, ktsiouni, mgrigori 
 *
 */
public class EventFactory {

	
	/**
	 * This is an implementation of the Factory Method design pattern
	 * Creates an instance of any of the subclasses derived from the top level class AbstractEvent
	 * 
	 * @param eventType a member of the {@link EventType} enumeration
	 * @param eventPublisherId a number generated by invoking the  {@link AbstractPublisher#hashCode()} on the {@link AbstractPublisher} instance issuing the event
	 * @param payload an object of type {@link EventMessage}
	 * @return
	 */
	public static AbstractEvent createEvent(EventType eventType, int eventPublisherId, EventMessage payload) {
		AbstractEvent event;
		switch (eventType) {
		case Fictional : 
			return new FictionalEvent(eventPublisherId, eventPublisherId, payload);
		case News : 
			return new NewsEvent(eventPublisherId, eventPublisherId, payload);
		case Scholarly:
			return new ScholarlyEvent(eventPublisherId, eventPublisherId, payload);
		default: 
			return new DefaultEvent(eventPublisherId, eventPublisherId, payload);
	}}
	
}
