package events;

import publishers.AbstractPublisher;
import publishers.ConcretePublisher;
import strategies.publisher.StrategyFactory;


/**
 * @author kkontog, ktsiouni, mgrigori 
 *
 */
public class EventFactory {

	
	/**
	 * This is an implementation of the Factory Method design pattern
	 * Creates an instance of any of the subclasses derived from the top level class AbstractEvent
	 * 
	 * @param eventType a member of the {@link EventType} enumeration
	 * @param eventPublisherId a number generated by invoking the  {@link AbstractPublisher#hashCode()} on the {@link AbstractPublisher} instance issuing the event
	 * @param payload an object of type {@link EventMessage}
	 * @return
	 */
	public static AbstractEvent createEvent(String eventType, int eventPublisherId, EventMessage payload) {
		switch (eventType) {
		case "Fictional": 
			return new FictionalEvent(EventIDMaker.getNewEventID(), eventPublisherId, payload);
		case "News" : 
			return new NewsEvent(EventIDMaker.getNewEventID(), eventPublisherId, payload);
		case "Scholarly":
			return new ScholarlyEvent(EventIDMaker.getNewEventID(), eventPublisherId, payload);
		default: 
			return new DefaultEvent(EventIDMaker.getNewEventID(), eventPublisherId, payload);
	}}
	
}